# Generated by Django 6.0 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('anno_uscita', models.IntegerField(blank=True, null=True)),
                ('posizione_fisica', models.CharField(help_text='Dove si trova la copia fisica?', max_length=100)),
                ('imdb_tmdb_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID IMDB/TMDB')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo Album/Singolo')),
                ('numero_disco', models.PositiveIntegerField(default=1, verbose_name='Numero Disco')),
                ('anno_uscita', models.IntegerField(blank=True, null=True)),
                ('artista', models.CharField(help_text='Se più artisti, separali con una virgola', max_length=200)),
                ('posizione_fisica', models.CharField(help_text='Dove si trova la copia fisica?', max_length=100)),
                ('lastfm_url', models.URLField(blank=True, null=True, verbose_name='URL Last.fm')),
            ],
            options={
                'verbose_name_plural': 'Musica',
            },
        ),
    ]
