# Generated by Django 6.0 on 2025-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.URLField(blank=True, null=True, verbose_name='URL Poster'),
        ),
        migrations.AddField(
            model_name='film',
            name='trama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
