# Generated by Django 6.0 on 2025-12-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_voto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musica',
            options={},
        ),
        migrations.RemoveField(
            model_name='musica',
            name='anno_uscita',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='lastfm_url',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='numero_disco',
        ),
        migrations.AddField(
            model_name='musica',
            name='copertina',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='spotify_url',
            field=models.URLField(blank=True, help_text="Incolla qui il link dell'album da Spotify", null=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musica',
            name='posizione_fisica',
            field=models.CharField(default='Libreria', max_length=100),
        ),
        migrations.AlterField(
            model_name='musica',
            name='titolo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
