# Generated by Django 6.0 on 2025-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_musica_options_remove_musica_anno_uscita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='anno_uscita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='posizione_fisica',
            field=models.CharField(default='Libreria', help_text='Dove si trova la copia fisica?', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='titolo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='musica',
            name='posizione_fisica',
            field=models.CharField(default='Libreria', help_text='Dove si trova la copia fisica?', max_length=100),
        ),
    ]
