# Generated by Django 6.0 on 2025-12-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_musica_anno_uscita_alter_film_posizione_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='catalogo.film'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voti', to='catalogo.musica'),
        ),
    ]
