# Generated by Django 6.0 on 2025-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='media_type',
            field=models.CharField(choices=[('vhs', 'VHS'), ('bray', 'Blu-ray'), ('dvd', 'DVD'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='musica',
            name='media_type',
            field=models.CharField(choices=[('vinyl', 'Vinile'), ('cass', 'Cassetta'), ('cd', 'CD'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
